### ISSUE TITLE
Minor updates to pr-compliance.yml

### ISSUE THREAD

**Issue by mtfoley** [edenmind/OpenArabic#732]
**Is your feature request related to a problem? Please describe.**
I saw that you had begun using `mtfoley/pr-compliance-action`! I noticed a couple of things about your workflow file and I wanted to share them.
```yaml
name: PR Compliance
on:
  # should be pull_request_target, to deal with incoming PRs not initiated by those with write access to repos.
  # after seeing this, I updated the README on the action.
  pull_request:
    types: [opened, edited, reopened]

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

jobs:
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          # this line is probably unnecessary. if unspecified, the action 
          # will use the default branch name for comparisons.
          protected-branch: "main"
          # this line is probably unnecessary, as the input defaults to true.
          ignore-team-members: true
          # first entry should read `mobile/package.json`. from what 
          # I have seen, the "/.../pulls/{number}/files" API endpoint 
          # does not use dot notation in file paths.
          watch-files: |
            ./mobile/package.json
```

**Describe the solution you'd like**
There are a handful of changes in an incoming PR.

**Describe alternatives you've considered**
N/A

**Additional context**
This has shown one me one or two improvements I could make on the original action, especially docs.
